apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sealedsecretcontrollers.bitnami.com
spec:
  group: bitnami.com
  names:
    kind: SealedSecretController
    listKind: SealedSecretControllerList
    plural: sealedsecretcontrollers
    singular: sealedsecretcontroller
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
